version: '3.7'
services:
  # Service and dependencies
  # ------------------------
  app:
    build:
      context: .
      target: service
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis
    container_name: readings
    ports:
      - '6379:6379'

  # Tests
  # -----
  integration:
    build:
      context: .
      target: test
    depends_on:
      - app
    command: npm run test:integration
    environment:
      - APP_HOST=http://app:3000
